/* Construction properties only: not exam items or claims of AI accuracy. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const sandbox={window:{}};
for(const file of ['math-input.js','construction-board.js','scene-audit.js','answer-geometry.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist',file),'utf8'),sandbox);
const {DongConstruct:construct,DongSceneAudit:audit,DongAnswerGeometry:geometry}=sandbox.window;
const copy=value=>JSON.parse(JSON.stringify(value));let checks=0;
const test=fn=>{fn();checks++;};
const base={type:'circle',h:2,k:1,r:3,showDynamic:false,points:{A:[5,1],B:[2,4],C:[-1,1],O:[2,1],P:[8,6]},objects:[],lines:[]};
const install=(scene,answer,index=1)=>geometry.install(scene,[{index,answer,steps:[]}],construct);
const node=(scene,label)=>scene.objects.find(value=>value.label===label);
const resolve=(scene,label)=>audit.frame(scene,construct).engine.resolve(node(scene,label)?.id);
const coords=(scene,label)=>{const point=resolve(scene,label);return point&&[point.x,point.y];};
for(const [text,expected,op,parameters] of [
  ['S为P关于x轴的对称点。',[8,-6],'reflect_axis',{axis:'x',axisValue:0}],
  ['P关于y轴的对称点记为S。',[-8,6],'reflect_axis',{axis:'y',axisValue:0}],
  ['S为点P关于点O的对称点。',[-4,-4],'reflect_center',{}],
  ['点P关于点O的对称点为S。',[-4,-4],'reflect_center',{}],
  ["A'为A关于x轴的对称点。",[5,-1],'reflect_axis',{axis:'x',axisValue:0}],
  ['P_{12}为P关于y轴的对称点。',[-8,6],'reflect_axis',{axis:'y',axisValue:0}]
])test(()=>{const scene=copy(base),report=install(scene,text),label=text.includes("A'")?'A′':text.includes('12')?'P12':'S';assert.deepEqual(coords(scene,label),expected,text);assert.equal(node(scene,label).op,op);for(const [key,value]of Object.entries(parameters))assert.equal(node(scene,label)[key],value);assert.equal(report.unresolved.length,0);assert(audit.inspect(scene,'',[{answer:text}],construct).checks.some(value=>value.kind===op&&value.passed));});
test(()=>{const scene=copy(base);install(scene,'S为P关于x轴的对称点。R为S关于点O的对称点。连接PR。');scene.points.P=[4,-2];assert.deepEqual(coords(scene,'S'),[4,2]);assert.deepEqual(coords(scene,'R'),[0,0]);assert.equal(resolve(scene,'PR').type,'line');});
test(()=>{const scene=copy(base),report=install(scene,'S为U关于x轴的对称点。R为P关于点Z的对称点。');assert.equal(scene.objects.length,0);assert(report.unresolved.some(value=>value.label==='S'));assert(report.unresolved.some(value=>value.label==='R'));});
test(()=>{const scene=copy(base);install(scene,'如果S为P关于x轴的对称点，讨论其性质。不能作点P处的切线。');assert.equal(scene.objects.length,0);});
test(()=>{const scene=copy(base);scene.objects.push({id:'manualS',kind:'point',source:'user',label:'S',x:8,y:-6});const report=install(scene,'S为P关于x轴的对称点。');assert(report.unresolved.some(value=>value.label==='S'&&value.dependencyUnconfirmed));assert.equal(node(scene,'S').kind,'point');scene.points.P=[9,7];assert.deepEqual(coords(scene,'S'),[8,-6]);});
test(()=>{const scene=copy(base);scene.objects.push({id:'manualS',kind:'point',source:'user',label:'S',x:12,y:10});const before=copy(scene.objects[0]),report=install(scene,'S为P关于x轴的对称点。');assert(report.conflicts.some(value=>value.label==='S'));assert.deepEqual(scene.objects[0],before);});
test(()=>{const scene=copy(base);scene.objects.push({id:'manualS',kind:'construction',source:'user',label:'S',op:'reflect_axis',refs:['feature:P'],axis:'y',axisValue:0});const report=install(scene,'S为P关于x轴的对称点。');assert(report.conflicts.some(value=>value.label==='S'));assert.equal(node(scene,'S').axis,'y');});
test(()=>{const scene=copy(base);scene.objects.push({id:'manualS',kind:'construction',source:'user',label:'S',op:'reflect_axis',refs:['feature:P'],axis:'x',axisValue:0});const report=install(scene,'S为P关于x轴的对称点。');assert.equal(report.conflicts.length,0);assert.equal(report.unresolved.length,0);scene.points.P=[4,-2];assert.deepEqual(coords(scene,'S'),[4,2]);});
test(()=>{const scene=copy(base);install(scene,'在C点处的切线记为tC。在A点和B点处的切线分别记为t_A、t_B，切线t_A与切线t_B交于点T。');assert.equal(scene.objects.filter(value=>value.op==='tangent').length,3);assert.deepEqual(coords(scene,'T'),[5,4]);assert.deepEqual(Array.from(node(scene,'T').refs),[node(scene,'A 点切线').id,node(scene,'B 点切线').id]);assert.deepEqual(Array.from(node(scene,'A 点切线').aliases),['tA']);assert.equal(audit.inspect(scene,'直线tA与直线tB交于点T。',[],construct).missingLines.length,0);});
test(()=>{const scene=copy(base);install(scene,'在C点处的切线。在A、B两点处的切线，两条切线交于点T。');assert.deepEqual(coords(scene,'T'),[5,4],'Clause-local pair takes priority over unrelated visible tangent');});
test(()=>{const scene=copy(base),report=install(scene,'在A点处的切线，在B点处的切线，在C点处的切线，两条切线交于点T。');assert(!node(scene,'T'));assert(report.unresolved.some(value=>value.label==='T'));});
test(()=>{const scene=copy(base);scene.lines.push({id:'manual-l1',kind:'line',label:'l1',source:'user',m:0,b:0});const before=copy(scene.lines[0]),report=install(scene,'A、B两点处的切线分别为l1、l2，直线l1与l2交于T。');assert(!node(scene,'T'),'Conflicting alias must not use the unrelated manual line to guess T');assert(report.unresolved.some(value=>value.label==='l1'&&value.dependencyUnconfirmed));assert.deepEqual(scene.lines[0],before);});
test(()=>{const scene=copy(base);scene.objects.push({id:'existing-tangent',source:'given',op:'tangent',kind:'construction',label:'已有切线',refs:['feature:A','$conic']});const report=install(scene,'A、B两点处的切线分别为l1、l2，l1与l2交于T。');assert(!node(scene,'T'));assert(!scene.objects[0].aliases);assert(report.unresolved.some(value=>value.label==='l1'&&value.dependencyUnconfirmed));});
test(()=>{const scene=copy(base);scene.objects.push({id:'existing-tangent',source:'given',op:'tangent',kind:'construction',label:'l1',refs:['feature:A','$conic']});install(scene,'A、B两点处的切线分别为l1、l2，l1与l2交于T。');assert.deepEqual(coords(scene,'T'),[5,4]);});
test(()=>{const scene=copy(base);install(scene,'A、B两点处的切线分别为l1、l2。点P到直线l1的垂足为H。');assert.deepEqual(coords(scene,'H'),[5,6]);});
test(()=>{const scene=copy(base);scene.objects.push({id:'movingA',kind:'construction',op:'point_on',refs:['$conic'],t:0,label:'U'},{id:'movingB',kind:'construction',op:'point_on',refs:['$conic'],t:Math.PI,label:'V'});const text='U、V两点处的切线分别为l1、l2，l1与l2交于Q。连接PQ。M为PQ的中点。';const report=install(scene,text);assert(node(scene,'Q')?.deferredConstruction);assert(node(scene,'PQ')?.deferredConstruction);assert(node(scene,'M')?.deferredConstruction);assert.equal(resolve(scene,'Q'),null);assert.equal(resolve(scene,'M'),null);assert(report.unresolved.some(value=>value.label==='Q'));assert(audit.inspect(scene,'', [{answer:text}],construct).unavailable.includes('Q'));const count=scene.objects.length;node(scene,'V').t=Math.PI/2;assert.deepEqual(coords(scene,'Q'),[5,4]);assert.deepEqual(coords(scene,'M'),[6.5,5]);assert.equal(resolve(scene,'PQ').type,'line');assert.equal(install(scene,text).unresolved.length,0);assert.equal(scene.objects.length,count);node(scene,'V').t=Math.PI;assert.equal(resolve(scene,'Q'),null);assert(audit.inspect(scene,'',[{answer:text}],construct).invalid.includes('PQ'));});
test(()=>{const scene=copy(base),report=install(scene,'直线AC与AC交于R。连接PR。');assert(!node(scene,'R'));assert(!node(scene,'PR'));assert(report.unresolved.some(value=>value.label==='R'));});
test(()=>{const scene=copy(base);scene.objects.push({id:'manual-circle',kind:'circle',label:'l',h:0,k:0,r:2,source:'user'},{id:'manual-line',kind:'line',label:'m',m:0,b:0,source:'user'});const report=install(scene,'直线l与m交于点T。');assert(!node(scene,'T'),'A circle is not the explicitly referenced straight line');assert(report.unresolved.some(value=>value.label==='T'));});
for(const op of ['segment','ray'])test(()=>{const scene=copy(base);scene.points={A:[0,0],B:[1,0],C:[2,-1],D:[2,1]};scene.objects.push({id:'manual-bounded',kind:'construction',label:'AB',op,refs:['feature:A','feature:B'],source:'user'});const before=copy(scene.objects[0]);install(scene,'直线AB与CD交于点T。');assert.deepEqual(coords(scene,'T'),[2,0]);assert.deepEqual(scene.objects[0],before);assert(scene.objects.some(value=>value.op==='line'&&value.label==='AB'));const size=scene.objects.length;assert.equal(install(scene,'直线AB与CD交于点T。').unresolved.length,0);assert.equal(scene.objects.length,size);});
test(()=>{const scene=copy(base);scene.points={A:[0,0],B:[1,0],C:[2,-1],D:[2,1]};scene.lines.push({id:'manual-through',kind:'through_points',label:'AB',a:'A',b:'B',infinite:false,source:'user'});const before=copy(scene.lines[0]);install(scene,'直线AB与CD交于点T。');assert.deepEqual(coords(scene,'T'),[2,0]);assert.deepEqual(scene.lines[0],before);});
for(const text of ['不要设N为AB的中点。','不应作A点处的切线。','误以为N为AB的中点。','无需作A点处的切线。','并非N为AB的中点。','不必作A点处的切线。'])test(()=>{const scene=copy(base);install(scene,text);assert.equal(scene.objects.length,0,text);});
test(()=>{const scene=copy(base);geometry.install(scene,[{index:1,answer:'S为P关于x轴的对称点。',steps:[]},{index:2,answer:'S为P关于x轴的对称点，连接AS。',steps:[]}],construct);assert.deepEqual(Array.from(node(scene,'S').parts),[1,2]);const count=scene.objects.length;install(scene,'S为P关于x轴的对称点。',2);assert.equal(scene.objects.length,count);});
for(const text of ['S为P关于x轴的对称点。','P关于y轴的对称点记为S。','S为P关于点O的对称点。','P关于O的对称点为S。'])test(()=>{const names=Array.from(audit.declared(text));assert(names.includes('S'));assert(names.includes('P'));if(text.includes('O'))assert(names.includes('O'));});
test(()=>{const scene=copy(base);const report=geometry.install(scene,[{index:1,answer:'A、B两点处的切线分别为l1、l2。'},{index:2,answer:'两条切线交于点T。'}],construct);audit.prepare(scene,'已知点A、B。',[],construct);assert.deepEqual(coords(scene,'T'),[5,4],'A later part may refer to the unique pair established earlier');assert(audit.visible(node(scene,'A 点切线'),2));assert(audit.visible(node(scene,'B 点切线'),2));assert.equal(report.unresolved.length,0);});
test(()=>{const scene=copy(base);geometry.install(scene,[{index:1,answer:'A、B两点处的切线分别为l1、l2，l1与l2交于点T。'},{index:2,answer:'由点T可得结论。'}],construct);audit.prepare(scene,'已知点A、B。',[],construct);assert(audit.visible(node(scene,'T'),2),'Mentioning an established point shares it without repeating its definition');assert(audit.visible(node(scene,'A 点切线'),2),'Required upstream lines follow the referenced point');});
test(()=>{const scene=copy(base);geometry.install(scene,[{index:1,answer:'A、B两点处的切线分别为l1、l2。'},{index:2,answer:'由直线l1可得结论。'}],construct);assert(audit.visible(node(scene,'A 点切线'),2));assert(!audit.visible(node(scene,'B 点切线'),2),'Unreferenced auxiliary line stays in its original part');});
test(()=>{const scene=copy(base),report=geometry.install(scene,[{index:1,answer:'A、B两点处的切线。在C点处的切线。'},{index:2,answer:'两条切线交于点T。'}],construct);assert(!node(scene,'T'));assert(report.unresolved.some(n=>n.label==='T'),'Three earlier tangents do not determine which pair was intended');});
test(()=>{const scene=copy(base);install(scene,'N为AB的中点。');node(scene,'N').part=1;delete node(scene,'N').parts;const before=copy(node(scene,'N'));install(scene,'由点N可得结论。',2);assert.deepEqual(copy(node(scene,'N')),before,'Explicit part assignment is retained');});
test(()=>{const scene=copy(base);scene.objects.push({id:'manualN',kind:'point',label:'N',x:1,y:1,part:1,source:'user'});const before=copy(scene.objects[0]);install(scene,'由点N可得结论。',2);assert.deepEqual(scene.objects[0],before);});
test(()=>{const scene=copy(base);install(scene,'A、B两点处的切线。');node(scene,'A 点切线').visible=false;install(scene,'两条切线交于点T。',2);assert(!node(scene,'T'),'A manually hidden tangent is not silently selected as the unnamed pair');assert.equal(node(scene,'A 点切线').visible,false);});
test(()=>{const scene=copy(base),report=geometry.install(scene,[{index:1,answer:'N为AB的中点。'},{index:2,answer:'N为AC的中点，连接PN。M为PN的中点。'}],construct);assert(report.conflicts.some(n=>n.label==='N'&&n.part===2));assert.deepEqual(Array.from(node(scene,'N').parts),[1],'Conflicting definition must not share the old point');assert(!node(scene,'PN'),'Same-clause connection must not use the wrong N');assert(!node(scene,'M'),'Downstream midpoint must not use the wrong N');assert.deepEqual(coords(scene,'N'),[3.5,2.5]);});
test(()=>{const scene=copy(base);scene.points.C=[2,4];const report=geometry.install(scene,[{index:1,answer:'N为AB的中点。'},{index:2,answer:'N为AC的中点。连接PN。'}],construct);assert(report.unresolved.some(n=>n.label==='N'&&n.dependencyUnconfirmed));assert.deepEqual(Array.from(node(scene,'N').parts),[1]);assert(!node(scene,'PN'),'Coincidence is not identity of dependencies');});
test(()=>{const scene=copy(base);geometry.install(scene,[{index:1,answer:'N为AB的中点。'},{index:2,answer:'N为AC的中点。连接PN。'},{index:3,answer:'N为AB的中点。连接PN。'}],construct);assert.deepEqual(Array.from(node(scene,'N').parts),[1,3],'A conflict in part 2 does not poison an unambiguous part 3');assert.deepEqual(Array.from(node(scene,'PN').parts),[3]);});
test(()=>{const scene=copy(base),report=geometry.install(scene,[{index:1,answer:'N为AB的中点。'},{index:2,answer:'连接PN。M为PN的中点。N为AC的中点。'}],construct);assert(!node(scene,'PN'));assert(!node(scene,'M'));assert.deepEqual(Array.from(node(scene,'N').parts),[1]);assert(report.unresolved.some(n=>n.label==='M'&&n.part===2));assert(!report.added.some(n=>n.label==='M'));});
test(()=>{const scene=copy(base);geometry.install(scene,[{index:1,answer:'N为AB的中点。连接PN。'},{index:2,answer:'连接PN。N为AC的中点。'}],construct);assert(node(scene,'PN'),'Earlier construction is retained');assert.deepEqual(Array.from(node(scene,'PN').parts),[1],'Only newly inferred scope is rolled back');assert.deepEqual(Array.from(node(scene,'N').parts),[1]);});
test(()=>{const scene=copy(base);scene.objects.push({id:'n1',kind:'point',label:'N',part:1,x:1,y:1,source:'user'},{id:'n2',kind:'point',label:'N',part:2,x:2,y:2,source:'user'});geometry.install(scene,[{index:1,answer:'连接PN。'},{index:2,answer:'连接PN。'}],construct);const segments=scene.objects.filter(n=>n.op==='segment');assert.equal(segments.length,2);assert(segments.some(n=>n.refs[1]==='n1'&&n.parts.includes(1)));assert(segments.some(n=>n.refs[1]==='n2'&&n.parts.includes(2)));});
test(()=>{const scene=copy(base);scene.objects.push({id:'n1',kind:'point',label:'N',part:1,x:1,y:1,source:'user'},{id:'n2',kind:'point',label:'N',part:1,x:2,y:2,source:'user'});const report=install(scene,'N为AB的中点。连接PN。');assert.equal(scene.objects.length,2,'Ambiguous existing names must not create a third point');assert(report.unresolved.some(n=>n.label==='N'));});
test(()=>{const scene=copy(base);scene.objects.push({id:'n1',kind:'point',label:'N',part:1,x:1,y:1,visible:false,source:'user'},{id:'n2',kind:'point',label:'N',part:2,x:2,y:2,source:'user'});install(scene,'连接PN。');assert.equal(node(scene,'PN').refs[1],'n1','Hidden current-part point must not be replaced by another part point');assert.equal(scene.objects[0].visible,false);});
console.log('PASS answer dependency: '+checks+' symmetry, named-tangent, conservative-preservation, deferred-intersection and live-chain property checks');
