module.exports=async({page,context,assert,screenshot})=>{
  await page.evaluate(async()=>{for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();for(const k of await caches.keys())await caches.delete(k);sessionStorage.clear();});
  let transport='ok',hold=false,release,healthCalls=0;
  await context.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:true,requiresAuth:true};'}));
  await context.route('**/api/session',r=>r.fulfill({json:{token:'mobile-health-session',expires_in:600}}));
  await context.route('**/api/health',async r=>{
    healthCalls++;const captured=transport,authorized=!!r.request().headers().authorization;
    if(hold){hold=false;await new Promise(resolve=>release=resolve);}
    if(captured==='network')return r.abort('failed');
    if(captured==='limited')return r.fulfill({status:429,json:{error:'本日次数已用完，请明天再试。'}});
    if(captured==='expired')return r.fulfill({status:401,json:{error:'会话已过期'}});
    return r.fulfill({json:{app:'董解析',default_model:'test-cloud',capabilities:{transport:'sse'},engine:{remote:true,available:authorized,models:authorized?['test-cloud']:[]}}});
  });
  await page.reload({waitUntil:'domcontentloaded'});await page.setViewportSize({width:390,height:844});
  await page.locator('#question').fill('连接协议回归：保留当前题稿，不调用模型。');
  await page.locator('#openCloudAuth').click();await page.locator('#cloudAccessKey').fill('董老师666');
  const beforeLogin=healthCalls;await page.locator('#cloudLogin').click();
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
  await page.locator('#cloudAuthDialog').waitFor({state:'hidden'});
  assert(healthCalls-beforeLogin<=2,'Login reuses authenticated health instead of issuing duplicate expensive model checks');
  hold=true;release=null;await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state!=='failed');
  for(let i=0;i<50&&!release;i++)await page.waitForTimeout(20);assert(release,'The read-only health probe is held');
  await page.locator('#saveLocal').evaluate(n=>n.click());
  const drawingStatus=await page.locator('#status').textContent();assert.match(drawingStatus,/已保存/);
  await page.evaluate(()=>window.dispatchEvent(new Event('offline')));
  release();await page.waitForTimeout(200);
  assert.equal(await page.locator('#cloudConnection').getAttribute('data-state'),'failed','Late health success cannot paint offline state green');
  assert.match(await page.locator('#cloudConnectionText').textContent(),/设备已离线/);
  assert(!await page.locator('#engineStatus').evaluate(n=>n.classList.contains('ready')));
  assert.equal(await page.locator('#status').textContent(),drawingStatus,'Background connectivity does not replace the latest local action');
  // A forced online recheck is queued while an obsolete probe is in flight.
  hold=true;release=null;await page.evaluate(()=>window.dispatchEvent(new Event('online')));
  for(let i=0;i<50&&!release;i++)await page.waitForTimeout(20);assert(release);
  await page.evaluate(()=>{window.dispatchEvent(new Event('offline'));window.dispatchEvent(new Event('online'));});
  const beforeRelease=healthCalls;release();
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
  assert(healthCalls>beforeRelease,'Network recovery issues a fresh queued check');
  assert.equal(await page.locator('#status').textContent(),drawingStatus,'Recovery stays in the cloud badge, not the drawing status');
  transport='limited';await page.locator('#retryCloudConnection').evaluate(n=>n.click());
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='busy');
  assert.match(await page.locator('#cloudOutageMessage').textContent(),/稍后重试/);
  assert.doesNotMatch(await page.locator('#cloudOutageMessage').textContent(),/离线|口令错误|本机/);
  await screenshot('mobile-cloud-rate-limit-not-outage.png',null);
  transport='ok';await page.locator('#retryCloudConnection').click();
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
  let modelAttempts=0;
  await context.route('**/api/stream',r=>{modelAttempts++;return r.fulfill({status:429,json:{error:'本日解题次数已满，请稍后再试。'}});});
  const beforeLimitedSolve=healthCalls;await page.locator('#solveButton').click();
  await page.waitForFunction(()=>!document.querySelector('#solveButton').disabled&&document.querySelector('#cloudConnection').dataset.state==='busy');
  await page.waitForTimeout(150);
  assert.equal(modelAttempts,1,'A rejected solve is not automatically retried at the model endpoint');
  assert.equal(healthCalls,beforeLimitedSolve,'Cleanup does not erase the just-returned quota message with a green health badge');
  assert.match(await page.locator('#cloudOutageMessage').textContent(),/稍后重试/);
  await page.locator('#retryCloudConnection').click();await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
  transport='network';await page.locator('#retryCloudConnection').evaluate(n=>n.click());
  await page.locator('#cloudOutage').waitFor({state:'visible'});
  assert.match(await page.locator('#cloudOutageMessage').textContent(),/Wi-Fi.*移动数据/);
  assert.equal(await page.locator('#question').inputValue(),'连接协议回归：保留当前题稿，不调用模型。');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  transport='expired';await page.locator('#retryCloudConnection').click();
  await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='disconnected');
  assert(!await page.locator('#cloudOutage').isVisible());assert(!await page.evaluate(()=>window.DongRuntime.hasSession()));
};
