/* Alternative wording of a sourced original and explicit condition fixtures. */
const fs=require('node:fs'),path=require('node:path');
module.exports=async({page,context,assert,screenshot})=>{
 const bank=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/question-bank.json'),'utf8')).items,original=bank.find(q=>q.id==='2025-ii-16').question;let question=original,calls=0;
 await context.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:true,requiresAuth:false};'}));
 await context.route('**/api/health',r=>r.fulfill({json:{app:'董解析',capabilities:{transport:'sse'},engine:{available:true,remote:true,models:['fixture-cloud']}}}));
 await context.route('**/api/stream',r=>{calls++;const raw={title:'待校核回复',restatement:question,strategy:'原始回复保留',parts:[1,2].map(index=>({index,status:'partial',answer:'尚未求解',steps:['待解。']})),scene:{type:'ellipse',a:3,b:1,points:{},lines:[],constructions:[]}};return r.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(raw)}}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n'});});
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
 const read=()=>page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('zhigeometry:last')),f=window.DongSceneAudit.frame({...r.scene,activePart:r.activePart},window.DongConstruct);return{record:r,A:f.engine.resolve('area-chord-A'),B:f.engine.resolve('area-chord-B')};});
 for(const [input,kind] of [[original.replace('求 $|AB|$','求弦 $AB$ 的长度'),'wording'],[original.replace('两点，','两点，且 $A$ 在第一象限，'),'quadrant'],[original.replace('$(0,-2)$','$(-2,0)$').replace('两点，','两点，且直线 $l$ 的斜率大于 $0$，'),'swapped']]){
  question=input;await page.locator('#question').fill(question);await page.locator('#solveButton').click();await page.waitForFunction(()=>document.querySelector('#solveProgress').dataset.state==='complete'&&!document.querySelector('#solveButton').disabled);
  const before=await read();assert.equal(before.record.solution.completion.answered,2);assert.equal(before.record.solution.model_strategy,'原始回复保留');assert(before.record.solution.parts.every(p=>p.source==='symbolic-verified-override'));
  await page.locator('[data-study-part="2"]').click();await page.locator('#homeButton').click();if(!await page.locator('#areaChordPanel').evaluate(e=>e.open))await page.locator('#areaChordPanel summary').click();
  const now=await read(),spec=now.record.scene.areaChord;assert(await page.locator('#areaChordPanel').isVisible());assert.equal(await page.locator('[data-area-chord-choice]').count(),spec.solutions.length);assert.equal(await page.locator('#solution .katex-error').count(),0);assert.match(await page.locator('#metrics').textContent(),/△OAB · 面积/);
  if(kind==='quadrant'){assert(now.A.x>0&&now.A.y>0);assert(now.B.x>0&&now.B.y<0);assert.match(await page.locator('#areaChordReadout').textContent(),/A在第一象限/);assert.match(await page.locator('#areaChordReadout').textContent(),/面积及附加条件已保持/);}
  if(kind==='swapped'){assert(spec.swapped);assert.equal(spec.solutions.length,1);assert(Math.abs((now.B.y-now.A.y)/(now.B.x-now.A.x)-Math.SQRT1_2)<1e-7);assert.match(await page.locator('#areaChordReadout').textContent(),/斜率大于/);}
  await page.locator('[data-study-part="1"]').click();assert(!await page.locator('#areaChordPanel').isVisible());await page.locator('[data-study-part="2"]').click();assert.deepEqual((await read()).A,now.A);
 }
 assert.equal(calls,3);const saved=await read();await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-inspector-view="lesson"]').click();await page.locator('[data-study-part="2"]').click();assert.deepEqual((await read()).A,saved.A);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('[data-mobile-panel="board"]').click();if(!await page.locator('#areaChordPanel').evaluate(e=>e.open))await page.locator('#areaChordPanel summary').click();assert.match(await page.locator('#areaChordReadout').textContent(),/面积及附加条件已保持/);await page.locator('#unrestrictedMove').click();assert.match(await page.locator('#areaChordReadout').textContent(),/自由探索/);await page.locator('#unrestrictedMove').click();assert.match(await page.locator('#areaChordReadout').textContent(),/面积及附加条件已保持/);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await screenshot('condition-expression-'+width+'.png',null);await page.locator('#areaChordPanel summary').click();assert(!await page.locator('#areaChordPanel').evaluate(e=>e.open));}
};
