const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const box={window:{}};for(const f of ['math-input','number-display','equation-builder','question-parts','ellipse-distance','motion-domain','construction-board','scene-audit','basic-conditions','ellipse-area-chord'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/'+f+'.js'),'utf8'),box);
const {DongBasicConditions:basic,DongEllipseAreaChord:chord,DongSceneAudit:audit,DongConstruct:construct}=box.window,copy=x=>JSON.parse(JSON.stringify(x)),close=(a,b)=>assert(Math.abs(a-b)<1e-7*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`),bank=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/question-bank.json'),'utf8')).items,q=id=>bank.find(q=>q.id===id).question;let count=0;
const circle=basic.solve(q('2022-beijing-3'));assert(circle);close(circle.scene.h,.5);assert.match(circle.answer,/a=\\frac\{1\}\{2\}/);assert(circle.scene.lines.some(l=>l.label==='对称轴'));count++;
const para=basic.solve(q('2025-beijing-11'));assert(para);close(para.scene.p,3);assert.match(para.answer,/p=6/);assert.match(para.answer,/y\^2=12x/);count++;
const ellipse=basic.solve(q('2025-beijing-19-1'));assert(ellipse);close(ellipse.scene.a**2,4);close(ellipse.scene.b**2,2);count++;
for(const r of [circle,para,ellipse]){const report=audit.inspect(copy(r.scene),r.restatement,r.parts,construct);assert.equal(report.invalid.length,0);const f=audit.frame(r.scene,construct);if(r.scene.type==='circle'){const line=f.engine.resolve('basic-symmetry-axis');assert(line?.type==='line');close((r.scene.h-line.o.x)*line.d.y-(r.scene.k-line.o.y)*line.d.x,0);}count++;}
const original=q('2025-ii-16'),result=chord.solve(original);assert(result);assert.equal(result.completion.answered,2);assert.match(result.parts[1].answer,/\\sqrt\{5\}/);assert.match(result.parts[1].steps.join(' '),/面积为0|韦达/);assert.equal(result.scene.areaChord.solutions.length,2);count++;
const s=audit.prepare(copy(result.scene),original,result.parts);let frame=audit.frame(s,construct),A=frame.engine.resolve('area-chord-A'),B=frame.engine.resolve('area-chord-B');close(A.x*A.x/4+A.y*A.y/2,1);close(B.x*B.x/4+B.y*B.y/2,1);close(Math.abs(A.x*B.y-A.y*B.x)/2,Math.sqrt(2));close(Math.hypot(A.x-B.x,A.y-B.y),Math.sqrt(5));assert(!frame.engine.moveDriver('area-chord-A',{t:1}),'Given area is fixed until explicit exploration');count++;
const diagram=audit.inspect(copy(result.scene),original,result.parts,construct);for(const field of ['missing','answerMissing','missingLines','answerMissingLines','invalid','missingPolygons'])assert.equal(diagram[field].length,0,field);count++;
for(const [a,b,d,S] of [[2,Math.sqrt(2),-2,1],[2,Math.sqrt(2),2,Math.sqrt(2)],[3,2,1,.5],[3,2,2,1],[2,2,-3,1],[2,Math.sqrt(2),-2,.01]]){
 const rows=chord.candidates(a,b,d,S);assert(rows?.length);for(const r of rows){assert(r.D>0&&r.w>d*d);for(const p of r.points)close(p.x*p.x/(a*a)+p.y*p.y/(b*b),1);close(Math.abs(r.points[0].x*r.points[1].y-r.points[0].y*r.points[1].x)/2,S);close(r.length2,(1+r.k2)*(2*S/Math.abs(d))**2);assert(Math.hypot(r.points[0].x,r.points[0].y-d)>1e-8);}count++;
}
const four=chord.candidates(2,Math.sqrt(2),-2,1);assert.equal(four.length,4);assert(new Set(four.map(r=>r.length2.toFixed(8))).size===2,'Two different positive slope magnitudes can give different lengths');count++;
for(const args of [[2,1,2,2],[2,1,.2,1],[2,1,0,1],[2,1,2,0],[-2,1,2,1],[2,1,2,NaN]]){assert(!chord.candidates(...args)?.length);count++;}
for(const altered of [original+'\n（3）求面积。',original.replace('求 $|AB|$','求 $|AB|$ 与斜率'),original.replace('$(0,-2)$','$(1,-2)$'),original.replace('S_{\\triangle OAB}','S_{\\triangle PAB}'),original.replace('O$ 为坐标原点','P$ 为坐标原点'),original.replace('长轴长为 $4$','短轴长为 $4$'),original.replace('两点，','两点，且 $OA$ 垂直 $OB$，')]){assert.equal(chord.solve(altered),null,'Uncovered premises/goals are not silently discarded');count++;}
for(const altered of [q('2022-beijing-3')+'再求圆面积。',q('2022-beijing-3').replace('2x+y-1','y-1'),q('2025-beijing-11').replace('则 $p=$______','求焦点与准线'),q('2025-beijing-19-1').replace('求椭圆方程','求椭圆方程与周长'),q('2025-beijing-19-1').replace('离心率为 $\\dfrac{\\sqrt2}2$','离心率为 $2$'),q('2025-beijing-19-1').replace('求椭圆方程','求 $Z$ 的方程')]){assert.equal(basic.solve(altered),null);count++;}
const variants=[q('2025-ii-16').replace('$(0,-2)$','$(0,2)$'),q('2025-ii-16').replace('$(0,-2)$','$(-2,0)$'),q('2025-ii-16').replace('x^2}{a^2}+\\dfrac{y^2}{b^2}','y^2}{a^2}+\\dfrac{x^2}{b^2}'),q('2025-ii-16').replace('\\sqrt2$，求','1$，求')];
for(const input of variants){const r=chord.solve(input);assert(r);const spec=r.scene.areaChord;for(const solution of spec.solutions){const scene=copy(r.scene),t=chord.parameter(spec,solution),driver=scene.objects[0];driver.t=t;driver.motionDomain={parameter:{min:t,max:t}};const f=audit.frame(scene,construct),A=f.engine.resolve(driver.id),B=f.engine.resolve('area-chord-B');assert(A&&B);close(Math.abs(A.x*B.y-A.y*B.x)/2,spec.area);close(Math.hypot(A.x-B.x,A.y-B.y)**2,solution.length2);assert.equal(audit.inspect(scene,input,r.parts,construct).invalid.length,0);}count++;}
const named=original.replace(/\bC\b/g,'E').replace(/\bA\b/g,'P').replace(/\bB\b/g,'Q').replace(/\bO\b/g,'Z').replace(/OAB/g,'ZPQ').replace(/AB/g,'PQ');assert(chord.solve(named));count++;
const vertical=basic.solve(q('2025-beijing-19-1').replace('x^2}{a^2}+\\dfrac{y^2}{b^2}','y^2}{a^2}+\\dfrac{x^2}{b^2}'));assert(vertical);assert.equal(vertical.scene.orientation,'vertical');close(vertical.scene.a,2);count++;
const changedPara=basic.solve(q('2025-beijing-11').replace('y^2=2px','x^2=-4py'));assert(changedPara);close(changedPara.scene.value,3);assert.equal(changedPara.scene.direction,-1);assert.equal(changedPara.scene.orientation,'vertical');count++;
const changedCircle=basic.solve(q('2022-beijing-3').replace('2x+y-1','x+2y-1').replace('(x-a)^2+y^2','x^2+(y-a)^2'));assert(changedCircle);close(changedCircle.scene.k,.5);count++;
console.log('PASS condition models: '+count+' sourced, parameter, candidate completeness, domain, axis and scope checks');
