module.exports=async({page,assert,screenshot})=>{
  const solve=async text=>{
    await page.locator('#question').fill(text);
    await page.locator('#solveButton').click();
    await page.waitForFunction(()=>!document.querySelector('#solveButton').disabled);
    return JSON.parse(await page.locator('#sceneJson').inputValue());
  };
  const original='在平面直角坐标系中，椭圆 C：x²/4＋y²＝1 上有一动点 P，定点 A 的坐标为 (0，2)。求 PA 的最大值，并写出此时点 P 的坐标。';
  const scene=await solve(original);
  assert.deepEqual(scene.points.A,[0,2],'自然语言给出的定点坐标必须识别');
  assert(scene.objects.some(o=>o.label==='P'&&o.op==='point_on'),'必须识别曲线上动点');
  assert.match(await page.locator('#solution').innerText(),/已生成完整作答/);
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('#solution annotation')).some(n=>n.textContent.includes('\\frac{2\\sqrt{21}}{3}')));
  assert.equal(scene.objects.filter(o=>o.label==='P').length,1,'解答场景合并后不能重复创建动点');
  assert.equal(scene.distanceExtrema.length,1);
  assert.match(await page.locator('#metrics').innerText(),/2√21\/3/,'极值读数应保留根式');
  assert.match(await page.locator('#metrics').innerText(),/-2\/3/,'极值点坐标应保留分数');
  assert.equal(await page.locator('[data-distance-jump]').count(),2,'必须列出两个最大值位置');
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('[data-distance-jump="0:max:0"]').click();
  let moved=JSON.parse(await page.locator('#sceneJson').inputValue()).objects.find(o=>o.label==='P');
  assert(Math.abs(Math.sin(moved.t)+2/3)<1e-8);
  assert(Math.abs(2*Math.cos(moved.t)-2*Math.sqrt(5)/3)<1e-8);
  await page.locator('[data-distance-jump="0:max:1"]').click();
  moved=JSON.parse(await page.locator('#sceneJson').inputValue()).objects.find(o=>o.label==='P');
  assert(Math.abs(2*Math.cos(moved.t)+2*Math.sqrt(5)/3)<1e-8);
  await screenshot('ellipse-distance.png','.board-shell');
  await page.locator('#parameterTarget').selectOption('$conic');
  await page.locator('#unrestrictedMove').click();
  await page.locator('#params input[data-key="b"][data-param-expression="true"]').evaluate(el=>{el.value='0.5';el.dispatchEvent(new Event('input',{bubbles:true}));});
  const changed=JSON.parse(await page.locator('#sceneJson').inputValue());
  assert.equal(changed.b,0.5);
  const expected=await page.evaluate(s=>window.DongEllipseDistance.compute(s,s,s.points.A).max.distance,changed);
  const metric=await page.locator('#metrics .metric').filter({hasText:'|PA| 最大值'}).locator('.metric-value').innerText();
  const displayed=await page.evaluate(s=>window.DongEquationBuilder.scalar(s.replace(/^≈/,'')),metric);
  assert(Math.abs(displayed-expected)<1e-5,'参数变化后最大值标记必须重算');
  // A browser-only deployment must also solve a renamed, rotated problem.
  await page.route('**/api/**',route=>route.abort());
  await page.evaluate(()=>{window.DongRuntime.config.apiEnabled=false;});
  const rotated=await solve('已知椭圆 C：x²+y²/4=1，Q为椭圆上的动点，定点B(2,0)。求QB的最大值及此时Q的坐标。');
  assert.equal(rotated.distanceExtrema[0].moving,'Q');
  assert.equal(rotated.distanceExtrema[0].source,'B');
  assert.match(await page.locator('#solution').innerText(),/已生成完整作答/);
  const far=await solve('椭圆 C：x²/4+y²=1 上有一动点P，定点A(0,10)。求PA的最大值。');
  assert.equal(far.distanceExtrema.length,1);
  assert.equal(await page.locator('[data-distance-jump]').count(),1,'顶点不在区间内时，最大值仅在端点取得');
  assert.match(await page.locator('#solution').innerText(),/最大值为.*11/s);
  await solve('椭圆 C：x²/4+y²=1 上有一动点P，定点A(0,2)。(1)求PA的最小值。(2)求PA的最大值。');
  assert.equal(await page.locator('[data-distance-jump]').count(),1);
  await page.locator('[data-study-part="2"]').click();
  assert.equal(await page.locator('[data-distance-jump]').count(),2);
  await solve('椭圆 C：x²/4+y²=1 上有一动点P，定点A(0,2)，P在第一象限。(1)求PA的最大值。');
  assert.match(await page.locator('#solution').innerText(),/不存在最大值/,'象限开弧不能套用整个椭圆的最值');
  assert.equal(await page.locator('[data-distance-jump]').count(),0,'不可取得的上界不能定位到非法端点');
};
