/* User-supplied original; added conditions are domain fixtures, not exam items.
 * Cloud replies here are protocol fixtures, NOT paid model accuracy tests. */
module.exports=async({page,context,assert,screenshot})=>{
 const original='在平面直角坐标系中，椭圆 C：x²/4＋y²＝1 上有一动点 P，定点 A 的坐标为 (0，2)。';let input=original+'求PA的最大值。',calls=0;
 await context.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:true,requiresAuth:false};'}));
 await context.route('**/api/health',r=>r.fulfill({json:{app:'董解析',capabilities:{transport:'sse'},engine:{available:true,remote:true,models:['fixture-cloud']}}}));
 await context.route('**/api/stream',r=>{calls++;const parts=windowParts(input),reply={title:'待校核云回复',restatement:input,parts:parts.map(index=>({index,status:'partial',answer:'待解',steps:['待推导。']})),scene:{type:'ellipse',a:3,b:1,points:{A:[0,2]},lines:[],constructions:[{id:'cloud-moving',op:'point_on',label:'P',refs:['$conic'],t:.5}]}};return r.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(reply)}}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n'});});
 const windowParts=text=>text.includes('（2）')?[1,2]:[0];
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
 const read=()=>page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('zhigeometry:last')),s={...r.scene,activePart:r.activePart},f=window.DongSceneAudit.frame(s,window.DongConstruct),o=s.objects.find(o=>o.label==='P');return{record:r,P:f.engine.resolve(o.id),driver:f.engine.driver(o)};});
 const solve=async text=>{input=text;await page.locator('#question').fill(text);await page.locator('#solveButton').click();await page.waitForFunction(()=>!document.querySelector('#solveButton').disabled&&['complete','partial','error'].includes(document.querySelector('#solveProgress').dataset.state));return read();};
 let r=await solve(original+'P在第一象限。求PA的最大值。');assert.equal(r.record.solution.completion.answered,1);assert.match(r.record.solution.parts[0].answer,/不存在最大值/);assert.equal(r.record.scene.a,2,'Independent graph replaces a nonempty incompatible AI graph');assert(r.record.solution.model_scene);assert(r.P.x>0&&r.P.y>0);assert.equal(await page.locator('[data-distance-jump]').count(),0);assert.match(await page.locator('#metrics').textContent(),/上确界/);assert.equal(await page.locator('#solution .katex-error').count(),0);
 r=await solve(original+'P在第三象限。求PA的最大值。');assert.equal(await page.locator('[data-distance-jump]').count(),1);await page.locator('[data-inspector-view="geometry"]').click();await page.locator('[data-distance-jump]').click();r=await read();assert(r.P.x<0);assert(Math.abs(r.P.y+2/3)<1e-7);assert.equal(r.driver.motionDomain.quadrant,3);
 // Real pointer events, not a test-only mutation of the motion configuration.
 await page.locator('#homeButton').click();const canvas=await page.locator('#canvas').boundingBox(),scale=Math.max(7/canvas.width,4.72/canvas.height),xy=p=>({x:canvas.x+canvas.width/2+p.x/scale,y:canvas.y+canvas.height/2-p.y/scale});
 const drag=async(to)=>{const from=xy((await read()).P),end=xy(to);await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:10});await page.mouse.up();};
 await drag({x:-Math.sqrt(3),y:-.5});r=await read();assert(Math.abs(r.P.y+.5)<.03,'Pointer drag moves the curve-bound point');await drag({x:1,y:1});r=await read();assert(r.P.x<0&&r.P.y<0,'Pointer drag cannot leave the given quadrant');
 r=await solve(original+'P的纵坐标大于0。求PA的取值范围。');assert.match(r.record.solution.parts[0].answer,/\\in \[1,2\\sqrt\{2\}\)/);assert.equal(await page.locator('[data-distance-jump]').count(),1,'Only the attained minimum can be located');
 r=await solve(original+'（1）若P在第一象限，求PA的最大值。（2）若P在第三象限，求PA的最大值。');assert.equal(r.record.solution.completion.answered,2);assert(r.P.x>0&&r.P.y>0);assert.equal(r.driver.motionDomain.quadrant,1);await page.locator('[data-study-part="2"]').click();r=await read();assert(r.P.x<0&&r.P.y<0);assert.equal(r.driver.motionDomain.quadrant,3);await page.locator('[data-inspector-view="geometry"]').click();await page.locator('[data-distance-jump]').click();const attained=(await read()).P;
 await page.locator('[data-inspector-view="lesson"]').click();await page.locator('[data-study-part="1"]').click();assert.equal(await page.locator('[data-distance-jump]').count(),0);await page.locator('[data-study-part="2"]').click();assert.deepEqual((await read()).P,attained);
 await page.locator('#unrestrictedMove').click();assert.equal(await page.locator('[data-distance-jump]').count(),0);assert.match(await page.locator('#metrics').textContent(),/自由探索/);await page.locator('#unrestrictedMove').click();assert.deepEqual((await read()).P,attained);
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-inspector-view="lesson"]').click();await page.locator('[data-study-part="2"]').click();assert.deepEqual((await read()).P,attained);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('[data-mobile-panel="board"]').click();await page.locator('#distanceExtremaPanel').waitFor({state:'visible'});if(!await page.locator('#distanceExtremaPanel').evaluate(e=>e.open))await page.locator('#distanceExtremaPanel summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await page.locator('[data-distance-jump]').isVisible());await page.locator('[data-distance-jump]').click();assert.deepEqual((await read()).P,attained);await screenshot('ellipse-domain-'+width+'.png',null);await page.locator('#distanceExtremaPanel summary').click();assert(!await page.locator('#distanceExtremaPanel').evaluate(e=>e.open));}
 assert.equal(calls,4);
};
