const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const box={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/solution-review.js'),'utf8'),box);
const review=box.window.DongSolutionReview,copy=x=>JSON.parse(JSON.stringify(x));
const p=(index,status='answered')=>({index,status,answer:'协议占位结论',steps:['协议占位推导'],derivation:{proof_obligations:[]}});
let n=0;const check=fn=>{fn();n++;};
const previous={mode:'cloud-ai',restatement:'原题',parts:[p(1),p(2,'partial')],scene:{type:'circle',r:2},study:{notes:'保留笔记'},conversation:[{role:'user',content:'保留追问'}],sceneAudit:{missing:['N'],checks:[{label:'切线',passed:false}]}};
check(()=>assert.equal(review.inspect(previous).answered,1));
check(()=>assert.equal(review.inspect(previous).diagram,'incomplete'));
check(()=>assert.deepEqual(Array.from(review.inspect(previous).issues),['N','切线']));
check(()=>assert.equal(review.inspect({...previous,scene:null}).diagram,'not-generated'));
check(()=>assert.equal(review.complete({...p(1),derivation:{proof_obligations:['待证']}}),false));
check(()=>assert.equal(review.complete({...p(1),steps:[' ']}),false));
check(()=>assert.throws(()=>review.request(previous,'另一题'),/题目已修改/));
check(()=>assert.throws(()=>review.request(previous,'原题',99),/不存在/));
const data=review.request(previous,'原题',2);
check(()=>assert.equal(data.focus_part,2));
check(()=>assert.deepEqual(JSON.parse(data.repair_context).diagram_issues,['N','切线']));
const huge={...previous,parts:Array.from({length:12},(_,i)=>({...p(i),answer:'字'.repeat(6000),steps:Array(40).fill('推导'.repeat(1000)),derivation:{proof_obligations:Array(40).fill('字'.repeat(5000))}}))};
check(()=>{const bounded=review.request(huge,'原题');assert(bounded.repair_context.length<=16000);assert.equal(JSON.parse(bounded.repair_context).parts.length,12);});
const next={mode:'cloud-ai',restatement:'原题',parts:[p(1,'partial'),{...p(2),answer:'补全结论'}],scene:null,verification:{status:'fully-verified'}};
const merged=review.merge(previous,next);
check(()=>assert.equal(merged.parts[0].status,'answered'));
check(()=>assert.equal(merged.parts[1].answer,'补全结论'));
check(()=>assert.equal(merged.study.notes,'保留笔记'));
check(()=>assert.equal(merged.conversation[0].content,'保留追问'));
check(()=>assert.equal(merged.verification.status,'generated','Combining proofs resets whole-result trust'));
check(()=>assert.equal(merged.scene.r,2));
check(()=>assert.equal(merged.completion.answered,2));
check(()=>assert.equal(next.parts[0].status,'partial','No mutation of either source response'));
for(const change of [{restatement:'另一题'},{parts:[p(1)]},{parts:[p(1),p(1)]},{parts:[p(1),p(99)]}])check(()=>assert.throws(()=>review.merge(previous,{...next,...change}),/不属于|不完整/));
(async()=>{
  const {safeConstructionScene}=await import('../dist/scene-contract.mjs');
  const base={type:'ellipse',a:3,b:1,h:2,k:1,dynamicLine:false,points:{P:[5,1]},lines:[{kind:'through_points',a:'N',b:'F_1',label:'NF1'}],constructions:[{id:'mid',op:'midpoint',refs:['feature:O','feature:F2'],label:'N'},{id:'other',op:'segment',refs:['feature:N','feature:P'],label:'NP'}]};
  const safe=safeConstructionScene(base);
  check(()=>assert.equal(safe.valid,true,JSON.stringify(safe.warnings)));
  check(()=>assert.deepEqual(safe.scene.points.O,[0,0]));
  check(()=>assert.deepEqual(safe.scene.objects.find(n=>n.id==='mid').refs,['feature:O','feature:F₂']));
  check(()=>assert.deepEqual(safe.scene.objects.find(n=>n.id==='other').refs,['mid','feature:P']));
  check(()=>assert.deepEqual(safe.scene.objects.find(n=>n.label==='NF1').refs,['mid','feature:F₁']));
  check(()=>assert.equal(safeConstructionScene({...base,constructions:[{id:'N',op:'midpoint',refs:['feature:N','feature:O'],label:'N'}]}).valid,false,'Feature-name aliases must not hide cycles'));
  for(const type of ['circle','parabola'])check(()=>assert.equal(safeConstructionScene({type,r:2,p:1,constructions:[{id:'s',op:'segment',refs:['feature:F1','feature:O'],label:'s'}]}).valid,false,'Nonexistent foci are still rejected'));
  check(()=>assert.equal(safeConstructionScene({...base,points:{F1:[0,3]},lines:[{kind:'through_points',a:'F1',b:'O'}],constructions:[]}).scene.objects[0].refs[0],'feature:F1','An explicitly given point wins over the implicit alias'));
  const inversion={type:'ellipse',a:3,b:1,dynamicLine:false,points:{A:[0,-1]},curvePoints:[{name:'P',t:1}],constructions:[{id:'R',op:'inverse',refs:['feature:A','feature:P'],label:'R',power:3}]};
  check(()=>assert.equal(safeConstructionScene(inversion).valid,true));
  for(const power of [-1,0,Infinity,'3'])check(()=>assert.equal(safeConstructionScene({...inversion,constructions:[{...inversion.constructions[0],power}]}).valid,false));
  const {modelPayload}=await import('../deploy/cloudflare/worker.mjs');
  for(const file of ['motion-domain.js','construction-board.js','scene-audit.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/'+file),'utf8'),box);
  const anchored={type:'ellipse',a:Math.sqrt(12),b:3,points:{P:[3,1.5]},constructions:[{id:'secant',op:'line_angle',refs:['feature:P'],angle:90,label:'l'},{id:'other-point',op:'second_intersection',refs:['P','line:l','$conic'],label:'B'}]};
  const anchoredSafe=safeConstructionScene(anchored);
  check(()=>assert.equal(anchoredSafe.valid,true,JSON.stringify(anchoredSafe.warnings)));
  check(()=>assert.deepEqual(anchoredSafe.scene.objects[1].refs,['feature:P','secant','$conic']));
  const subscripted=safeConstructionScene({type:'circle',r:2,points:{B_1:[2,0]},constructions:[{id:'connector',op:'segment',refs:['B1','feature:O'],label:'s'}]});
  check(()=>assert.equal(subscripted.valid,true));
  check(()=>assert.deepEqual(subscripted.scene.objects[0].refs,['feature:B_1','feature:O']));
  check(()=>assert.equal(safeConstructionScene({type:'circle',r:2,points:{B_1:[2,0],'B₁':[0,2]},constructions:[{id:'connector',op:'segment',refs:['B1','feature:O'],label:'s'}]}).valid,false,'Ambiguous subscript aliases must not choose a point'));
  for(const angle of [0,30,90,120,180,270]){
    anchoredSafe.scene.objects[0].angle=angle;const current=box.window.DongSceneAudit.frame(anchoredSafe.scene,box.window.DongConstruct),B=current.engine.resolve('other-point');
    check(()=>{assert(B);assert(Math.hypot(B.x-3,B.y-1.5)>1e-7);assert(Math.abs(B.x*B.x/12+B.y*B.y/9-1)<1e-8);assert(Math.abs((B.x-3)*Math.sin(angle*Math.PI/180)-(B.y-1.5)*Math.cos(angle*Math.PI/180))<1e-8);});
  }
  anchoredSafe.scene.objects[0].angle=Math.atan(-1.5)*180/Math.PI;
  check(()=>assert.equal(box.window.DongSceneAudit.frame(anchoredSafe.scene,box.window.DongConstruct).engine.resolve('other-point'),null,'A tangent has no distinct other intersection'));
  check(()=>assert.equal(safeConstructionScene({...anchored,constructions:[{...anchored.constructions[1],refs:['P','$conic','line:l']}]}).valid,false));
  check(()=>assert.equal(safeConstructionScene({...anchored,constructions:[{...anchored.constructions[0]},{...anchored.constructions[1],refs:['P','line:unknown','$conic']}]}).valid,false));
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/conic-area.js'),'utf8'),box);
  for(const a of [2,3,7])for(const b of [1,1.5])for(const h of [-4,0,3])for(const t of [.3,1.2,2.8,4,5]){
    const k=2,A={x:h+a,y:k},P={x:h,y:k+b},B={x:h+a*Math.cos(t),y:k+b*Math.sin(t)},area=Math.abs((P.x-A.x)*(B.y-A.y)-(P.y-A.y)*(B.x-A.x))/2;
    const curve=box.window.DongConstruct.conicShape({conicType:'ellipse',a,b,h,k});
    const found=box.window.DongConicArea.candidates(curve,A,P,area,box.window.DongConstruct);
    check(()=>{assert(found.some(s=>Math.hypot(s.B.x-B.x,s.B.y-B.y)<1e-7));assert(found.every(s=>Math.abs(s.area-area)<1e-7));});
  }
  const curve=box.window.DongConstruct.conicShape({conicType:'ellipse',a:Math.sqrt(12),b:3,h:0,k:0}),A={x:0,y:3},P={x:3,y:1.5};
  const areaSolutions=box.window.DongConicArea.candidates(curve,A,P,9,box.window.DongConstruct);
  check(()=>assert.equal(areaSolutions.length,2));
  check(()=>assert(areaSolutions.some(s=>Math.hypot(s.B.x+3,s.B.y+1.5)<1e-8)));
  check(()=>assert(areaSolutions.some(s=>Math.hypot(s.B.x,s.B.y+3)<1e-8)));
  check(()=>assert.equal(box.window.DongConicArea.candidates(curve,A,P,0,box.window.DongConstruct),null,'Zero-area families require a separate degeneracy analysis'));
  check(()=>assert.equal(box.window.DongConicArea.candidates(curve,A,P,1000,box.window.DongConstruct).length,0));
  for(const file of ['math-input.js','equation-builder.js','number-display.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/'+file),'utf8'),box);
  // Excerpt of the actual 2023 II question 21 cloud reply recorded in this release.
  const wrong={index:2,answer:'$P$ 在定直线 $x=10$ 上。',steps:['联立得到 $-3(x+2)=x-2$，解得 $x=10$。']};
  const conflicts=review.algebraConflicts(wrong);
  check(()=>assert.equal(conflicts.length,1));
  check(()=>assert.equal(conflicts[0].expected,-1));
  check(()=>assert.equal(conflicts[0].claimed,10));
  check(()=>assert.equal(review.algebraConflicts({...wrong,answer:'P 在定直线 x=-1 上。',steps:['联立得到 $-3(x+2)=x-2$，解得 $x=-1$。']}).length,0));
  check(()=>assert.equal(review.algebraConflicts({...wrong,steps:['$x_1=-3$','$x^2=4$','$mx+y=1$']}).length,0,'Indexed coordinates, nonlinear and symbolic equalities are not treated as affine proofs'));
  check(()=>assert.equal(review.algebraConflicts({...wrong,answer:'满足条件时 x=10。'}).length,0,'Do not apply a fixed-line assertion check to unrelated case-specific coordinates'));
  check(()=>assert.equal(review.algebraConflicts({index:2,answer:'P 在定直线 x=-1 上。',steps:['当直线 $x=-4$ 时，与曲线交于两个点。','联立得 $-3(x+2)=x-2$，解得 $x=-1$。'],derivation:{equations:['x=-4','x=-1']}}).length,0,'A given chord equation must not be confused with the resulting fixed locus'));
  const context=review.request({...previous,sceneAudit:{checks:conflicts}},'原题',2);
  check(()=>assert.equal(JSON.parse(context.repair_context).algebra_issues[0].expected,-1));
  const graph=safeConstructionScene(inversion).scene;
  for(const t of [.2,1,2,3,4,5]){
    graph.objects.find(n=>n.label==='P').t=t;
    check(()=>assert(box.window.DongSceneAudit.inspect(graph,'点R',[],box.window.DongConstruct).checks.some(c=>c.kind==='inverse'&&c.passed)));
  }
  const shifted=safeConstructionScene(base).scene;
  check(()=>assert(box.window.DongSceneAudit.declared('过P的直线l交C于另一点B，求直线l').includes('B'),'A second intersection is still a declared question point'));
  check(()=>assert(review.inspect({...previous,scene_warnings:['焦点引用无效']}).issues.includes('焦点引用无效'),'Rejected graph diagnostics are supplied to explicit continuation'));
  check(()=>assert.equal(box.window.DongSceneAudit.inspect(shifted,'点N',[],box.window.DongConstruct).invalid.length,0));
  const {inspectGeometry}=await import('../dist/external-contract.mjs');
  check(()=>assert.deepEqual(inspectGeometry(shifted,box.window.DongConstruct),[],'Clipboard and cloud use the same intrinsic features'));
  check(()=>assert.equal(safeConstructionScene({type:'circle',h:3,k:4,r:6,dynamicLine:true,lineThrough:'point:O'}).valid,true));
  const input={kind:'solve',text:'（1）求方程；（2）求范围；（3）求坐标',model:'deepseek-flash',repair_context:data.repair_context,focus_part:2};
  check(()=>assert.equal(modelPayload(input,{}).max_tokens,9000));
  check(()=>assert.match(modelPayload(input,{}).messages[2].content,/内部编号 2/));
  check(()=>assert.throws(()=>modelPayload({...input,focus_part:99},{}),/不属于原题/));
  check(()=>assert.throws(()=>modelPayload({...input,repair_context:'x'.repeat(16001)},{}),/过长/));
  check(()=>assert.throws(()=>modelPayload({...input,repair_context:undefined},{}),/缺少/));
  check(()=>assert.equal(modelPayload({...input,repair_context:undefined,focus_part:undefined,text:'求坐标'},{}).max_tokens,6000));
  console.log('PASS solution review: '+n+' completion, bounded continuation, non-regression, intrinsic feature, dependency alias and inversion checks');
})().catch(e=>{console.error(e);process.exitCode=1;});
