/* Sourced 2022 I Q21 with deliberately incomplete cloud reply. Production
 * code must independently align the proof, constraints and complete diagram. */
const fs=require('node:fs'),path=require('node:path');
module.exports=async({page,context,assert,screenshot})=>{
  const q=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/question-bank.json'),'utf8')).items.find(q=>q.id==='2022-i-21').question;let calls=0;
  const raw={title:'未完成推导回放',restatement:q,strategy:'原始模型策略',assumptions:['模型未完成的假设'],parts:[{index:1,status:'partial',answer:'尚未确定斜率',steps:[]},{index:2,status:'partial',answer:'尚未确定面积',steps:[]}],scene:{type:'hyperbola',a:2,b:1,dynamicLine:false,points:{},constructions:[],lines:[]}};
  await context.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:true,requiresAuth:false};'}));
  await context.route('**/api/health',r=>r.fulfill({json:{app:'董解析',capabilities:{transport:'sse'},engine:{available:true,installed:true,remote:true,models:['fixture-cloud']},default_model:'fixture-cloud'}}));
  await context.route('**/api/stream',r=>{calls++;return r.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(raw)}}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n'});});
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#cloudConnection').dataset.state==='connected');
  await page.locator('#question').fill(q);await page.locator('#solveButton').click();await page.waitForFunction(()=>document.querySelector('#solveProgress').dataset.state==='complete'&&!document.querySelector('#solveButton').disabled);
  const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('zhigeometry:last'))),record=await read();assert.equal(calls,1);assert.equal(record.solution.completion.answered,2);assert(record.scene.symmetricChord);assert(record.solution.parts.every(p=>p.source==='symbolic-verified-override'));assert.equal(record.solution.model_scene.a,2);assert.equal(record.solution.model_strategy,'原始模型策略');
  for(const key of ['missing','answerMissing','missingLines','answerMissingLines','invalid','missingPolygons'])assert.equal(record.solution.sceneAudit[key].length,0,key);assert.equal(await page.locator('#solution .katex-error').count(),0);
  const get=()=>page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('zhigeometry:last')),s={...r.scene,activePart:r.activePart},f=window.DongSceneAudit.frame(s,window.DongConstruct);return{scene:s,features:f.features,P:f.engine.resolve('symmetric-chord-P'),Q:f.engine.resolve('symmetric-chord-Q')};});
  await page.locator('[data-study-part="all"]').click();let frame=await get();assert.equal(frame.scene.activePart,null);assert(Math.abs(Math.abs((frame.P.x-2)*(frame.Q.y-1)-(frame.P.y-1)*(frame.Q.x-2))/2-16*Math.sqrt(2)/9)<1e-7,'All-question view shows the answer configuration');
  await page.locator('[data-study-part="1"]').click();await page.locator('#homeButton').click();frame=await get();const oldQ={...frame.Q},box=await page.locator('#canvas').boundingBox();let rx=frame.scene.a*1.75,ry=frame.scene.b*1.9;for(const p of [...frame.features,frame.P,frame.Q]){rx=Math.max(rx,Math.abs(p.x)*1.18);ry=Math.max(ry,Math.abs(p.y)*1.18);}const scale=Math.max(2*rx/box.width,2*ry/box.height),xy=p=>({x:box.x+box.width/2+p.x/scale,y:box.y+box.height/2-p.y/scale}),target={x:Math.sqrt(2)*Math.cosh(.45),y:Math.sinh(.45)},from=xy(frame.P),to=xy(target);
  await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:12});await page.mouse.up();frame=await get();assert(Math.abs(frame.Q.y-oldQ.y)>.1);assert(Math.abs((frame.Q.y-frame.P.y)/(frame.Q.x-frame.P.x)+1)<1e-7);const firstPose={...frame.P};
  await page.locator('[data-study-part="2"]').click();await page.locator('#homeButton').click();await page.locator('#symmetricChordPanel summary').click();assert.match(await page.locator('#symmetricChordReadout').textContent(),/本问角度已固定/);
  frame=await get();const beforeSwap={P:{...frame.P},Q:{...frame.Q}};await page.locator('[data-symmetric-choice="1"]').click();frame=await get();assert(Math.hypot(frame.P.x-beforeSwap.Q.x,frame.P.y-beforeSwap.Q.y)<1e-7);assert(Math.hypot(frame.Q.x-beforeSwap.P.x,frame.Q.y-beforeSwap.P.y)<1e-7);await screenshot('symmetric-chord-answer-desktop.png',null);
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-inspector-view="lesson"]').click();await page.locator('[data-study-part="1"]').click();frame=await get();assert(Math.hypot(frame.P.x-firstPose.x,frame.P.y-firstPose.y)<1e-10,'Reload and question switching preserve the first-part drag');
  await page.locator('[data-study-part="2"]').click();await page.setViewportSize({width:390,height:844});await page.locator('[data-mobile-panel="board"]').click();await page.locator('#homeButton').click();if(!await page.locator('#symmetricChordPanel').evaluate(e=>e.open))await page.locator('#symmetricChordPanel summary').click();await page.locator('[data-symmetric-choice="0"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await screenshot('symmetric-chord-answer-390.png',null);
  await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await screenshot('symmetric-chord-answer-320.png',null);
};
