const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const box={window:{}};for(const f of ['math-input','number-display','equation-builder','question-parts','ellipse-distance','motion-domain','construction-board','scene-audit','symmetric-chord'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/'+f+'.js'),'utf8'),box);
const {DongSymmetricChord:solver,DongSceneAudit:audit,DongConstruct:construct,DongMotionDomain:domain}=box.window,copy=x=>JSON.parse(JSON.stringify(x)),close=(a,b)=>assert(Math.abs(a-b)<1e-7*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
const q=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/question-bank.json'),'utf8')).items.find(q=>q.id==='2022-i-21').question;let count=0;
const result=solver.solve(q);assert(result);assert.equal(result.completion.answered,2);assert.match(result.parts[0].answer,/=-1/);assert.match(result.parts[1].answer,/\\frac\{16\\sqrt\{2\}\}\{9\}/);assert.match(result.parts[1].steps.join(' '),/渐近线方向/);close(result.scene.a**2,2);close(result.scene.b**2,1);count++;
let s=copy(result.scene),frame=audit.frame(s,construct),P=frame.engine.resolve('symmetric-chord-P'),Q=frame.engine.resolve('symmetric-chord-Q');
const diagram=audit.inspect(s,q,result.parts,construct);for(const field of ['missing','missingLines','answerMissing','answerMissingLines','invalid','missingPolygons'])assert.equal(diagram[field].length,0,field);count++;
const target=solver.sample(s.symmetricChord,Math.sqrt(2));close(P.x,target.P.x);close(Q.y,target.Q.y);count++;
s.activePart=1;frame=audit.frame(s,construct);const before=frame.engine.resolve('symmetric-chord-Q');assert(frame.engine.moveDriver('symmetric-chord-P',{t:.45,branch:1}));frame=audit.frame(s,construct);P=frame.engine.resolve('symmetric-chord-P');Q=frame.engine.resolve('symmetric-chord-Q');assert(Math.abs(Q.y-before.y)>.1);close(P.x**2/2-P.y**2,1);close(Q.x**2/2-Q.y**2,1);close((Q.y-P.y)/(Q.x-P.x),-1);close((P.y-1)/(P.x-2)+(Q.y-1)/(Q.x-2),0);count++;
for(const p of solver.exclusions(s.symmetricChord)){const parameter=solver.parameter(s.symmetricChord,{x:p[0],y:p[1]});assert(!frame.engine.moveDriver('symmetric-chord-P',parameter),'Reject a vertical, horizontal, coincident or reflected-tangent endpoint');count++;}
const planePose=copy(s.objects[0].motionByPart[1]);s.activePart=2;frame=audit.frame(s,construct);assert(!frame.engine.moveDriver('symmetric-chord-P',{t:2,branch:-1}),'The area part keeps its given angle');P=frame.engine.resolve('symmetric-chord-P');Q=frame.engine.resolve('symmetric-chord-Q');close(Math.abs((P.x-2)*(Q.y-1)-(P.y-1)*(Q.x-2))/2,16*Math.sqrt(2)/9);s.activePart=1;assert.equal(JSON.stringify(s.objects[0].motionByPart[1]),JSON.stringify(planePose));count++;
// Algebraic parameter properties cover curves and points on both branches.
for(const [a2,b2,u,v] of [[2,1,2,1],[8,4,4,2],[2,1,-2,1],[4,3,2,0],[12,9,4,Math.sqrt(3)]]){
  const spec={a2,b2,a:Math.sqrt(a2),b:Math.sqrt(b2),u,v};
  for(const t of [.2,.45,1.2,2,3]){const f=solver.sample(spec,t);if(!f)continue;for(const p of [f.P,f.Q])close(p.x*p.x/a2-p.y*p.y/b2,1);close((f.P.y-v)/(f.P.x-u)+(f.Q.y-v)/(f.Q.x-u),0);if(v===0)close(f.P.x,f.Q.x);else close((f.Q.y-f.P.y)/(f.Q.x-f.P.x),-u*b2/(v*a2));count++;}
}
assert.equal(solver.family(3,1,1,1),null,'Two valid parameter roots are not collapsed into one');assert(solver.family(3,1,1,2),'A stricter given domain may select one root');assert.equal(solver.family(1,1,1,1),null);assert.equal(solver.family(2,1,1,2),null);count++;
const scaled=solver.solve(q.replace('A(2,1)','A(4,2)').replace('a^2-1','a^2-4').replace('a>1','a>2'));assert(scaled);close(scaled.scene.a**2,8);close(scaled.scene.b**2,4);assert.match(scaled.parts[1].answer,/\\frac\{64\\sqrt\{2\}\}\{9\}/);count++;
const vertex=solver.solve(q.replace('A(2,1)','A(2,0)'));assert(vertex);assert.match(vertex.parts[0].answer,/竖直|斜率不存在/);assert(vertex.scene.symmetricChord.angle.rejected.some(r=>/锐角/.test(r.reason)));count++;
const renamed=q.replace(/PAQ/g,'NET').replace(/\bA\b/g,'E').replace(/AP/g,'EN').replace(/AQ/g,'ET').replace(/P,Q/g,'N,T');const named=solver.solve(renamed);assert(named);assert.equal(named.scene.symmetricChord.A,'E');assert.equal(named.scene.symmetricChord.P,'N');count++;
for(const altered of [q+'\n（3）求离心率。',q.replace('斜率之和为 $0$','斜率之和为 $1$'),q.replace('a^2-1','a^2-3'),q.replace('求 $l$ 的斜率','求 $l$ 的斜率并求截距'),q.replace('的面积。','的面积与周长。'),q.replace('PAQ=','PQA='),q.replace('A(2,1)','A(3,1)'),q.replace('tan\\angle PAQ=2\\sqrt2','tan\\angle PAQ=-2'),q.replace('直线 $AP,AQ$','直线 $AP,AP$')]){assert.equal(solver.solve(altered),null,'Uncovered constraints or goals stay pending');count++;}
const clean=domain.validate({excludePoints:[[2,1],[-2,1]]});assert(!domain.accepts({motionDomain:clean},{x:2,y:1},{}));assert(domain.accepts({motionDomain:clean},{x:2.001,y:1},{}));assert.match(domain.describe({motionDomain:clean}),/不取点/);count++;
for(const bad of [{excludePoints:['2,1']},{excludePoints:[[2,Infinity]]},{excludePoints:[[1,2,3]]},{excludePoints:Array.from({length:13},()=>[1,2])},{excludePoints:[[1,'eval()']]}]){assert.throws(()=>domain.validate(bad));count++;}
console.log('PASS symmetric chord: '+count+' sourced, parameter, incidence, angle, vertical, boundary, scope and domain checks');
